// Code generated by goctl. DO NOT EDIT!
// Source: unifiedLogin.proto

//go:generate mockgen -destination ./unifiedlogin_mock.go -package unifiedloginclient -source $GOFILE

package unifiedloginclient

import (
	"context"

	pb "ZeroProject/Rpc/unifiedLogin/pb"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = pb.Request
	Response = pb.Response

	//提供RPC接口
	UnifiedLogin interface {
		LoginToken(ctx context.Context, in *Request) (*Response, error)
	}

	defaultUnifiedLogin struct {
		cli zrpc.Client
	}
)

func (m *defaultUnifiedLogin) LoginToken(ctx context.Context, in *Request) (*Response, error) {
	client := pb.NewUnifiedLoginClient(m.cli.Conn())
	return client.LoginToken(ctx,in)
}

func NewUnifiedLogin(cli zrpc.Client) UnifiedLogin {
	return &defaultUnifiedLogin{
		cli: cli,
	}
}
